package Model;

public enum Objectif {
    FANTOME, CRANE, GNOME, SCARABEE, FEE, LEZARD, SOURIS, LIVRE, BAGUE, HIBOUX, PAPILLON, GENIE, CHANDELIER, COURONNE, BOURSE, TRESOR, CARTE, CLES, CHAUVE_SOURIS, CASQUE, EPEE, DRAGON, EMERAUDE
}
