package Model;

/** ENUM DES OBJECTIFS DU JEU **/
public enum Objectif {
    ARAIGNEE, FANTOME, CRANE, GNOME, SCARABEE, FEE, LEZARD, SOURIS, LIVRE, BAGUE, HIBOUX, PAPILLON, GENIE, CHANDELIER, COURONNE, BOURSE, TRESOR, CARTE, CLES, CHAUVE_SOURIS, CASQUE, EPEE, DRAGON, EMERAUDE
}
